\subsection{Data input}
% ============================================================================
% Import libraries
<<message=FALSE>>=
require(ggplot2)
require(intervals)
require(plyr)
require(magrittr)
require(xtable)
source('~/src/git/cadmium/src/report/R/findMissingGenes.R')
source('~/src/git/cadmium/src/report/R/testSyntenicGaps.R')
source('~/src/git/cadmium/src/report/R/build_gene2int.R')
source('~/src/git/cadmium/src/report/R/loadData.R')

# TODO REMOVE THIS IN PRODUCTION CODE
args <- list(
    query_gff = '~/src/git/cadmium/input/gff/Arabidopsis_thaliana.gff',
    synteny   = '~/src/git/cadmium/input/syn/Arabidopsis_thaliana.vs.Arabidopsis_lyrata.syn',
    nstring   = '~/src/git/cadmium/input/stat/nstrings.tab'
)
@

\subsection{Summaries of input data}
% ============================================================================
% Load all input data
<<cache=TRUE, warning=FALSE, message=FALSE>>=
syn <- LoadSyntenyMap(args$synteny)
gff <- LoadGFF(args$query_gff, features='mRNA')
nstring <- LoadNString(args$nstring)
@

\subsection{Gene feature format file for focal species}
<<results='asis', cache=TRUE>>=
plyr::ddply(
    annotation(gff),
    'seq_name',
    summarize,
    mRNAs=length(seq_name)
) %>% xtable
@

\subsection{Syntenic ouput of SatsumaSynteny}
<<results='asis', cache=TRUE>>=
plyr::ddply(
    annotation(syn$query),
    'seq_name',
    summarize,
    N.synteny.blocks=length(seq_name)
) %>% xtable
@

% TODO: Sync the TestSyntenicGaps code with new genomeIntervals implementation
% % ============================================================================
% \begin{figure}[!hbpt]
% <<fig.width=8, fig.height=8, cache=TRUE>>=
% TestSyntenyGaps(syn, nstring)
% @
% \caption{In black: missing regions on the target between syntenic blocks. In
%     red: strings of N's, bases that have not been correctly sequenced}
% \end{figure}

\begin{figure}[!ht]
    \centering
<<cache=TRUE>>=
lograt <- log2(size(syn$query) / size(syn$target)[syn$query$over])
lograt <- lograt[abs(lograt) > 0.25] 
plot(
    lograt,
    xlab='Ordered position on query genome',
    ylab='log2 of query to target length ratio'
)
abline(0, 0)
@
    \caption{\textbf{Diagnostic plot of query to target lengths in synteny
        map}. The syntenic intervals on the query and target sides should
        be of similar length.  They will not be exactly the same size if gaps
        are allowed in the alignment, but wild deviation from 0 (more than,
        say, 2) indicates errors in the input. To avoid overplottin, values
        between -0.25 and 0.25 are not plotted.} 
\end{figure}
